# Generated by Django 4.2.5 on 2023-09-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_s', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='accredat',
            field=models.DateField(),
        ),
    ]
